// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAfcaRaMNz9-KkzB2wn47ZJMFahZcthYg',
    appId: '1:624028473738:web:32493905dfa32613855073',
    messagingSenderId: '624028473738',
    projectId: 'reading-app-da2c7',
    authDomain: 'reading-app-da2c7.firebaseapp.com',
    databaseURL: 'https://reading-app-da2c7.firebaseio.com',
    storageBucket: 'reading-app-da2c7.firebasestorage.app',
    measurementId: 'G-L309EDTBJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKUgerIHMehCRsSmzcVg3heGiSzHdXiYo',
    appId: '1:624028473738:android:6bb402b3949c856d855073',
    messagingSenderId: '624028473738',
    projectId: 'reading-app-da2c7',
    databaseURL: 'https://reading-app-da2c7.firebaseio.com',
    storageBucket: 'reading-app-da2c7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQKmMOU091cOa3ACXhKKfhKW3UVNfZypU',
    appId: '1:624028473738:ios:63300a820f52f625855073',
    messagingSenderId: '624028473738',
    projectId: 'reading-app-da2c7',
    databaseURL: 'https://reading-app-da2c7.firebaseio.com',
    storageBucket: 'reading-app-da2c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQKmMOU091cOa3ACXhKKfhKW3UVNfZypU',
    appId: '1:624028473738:ios:63300a820f52f625855073',
    messagingSenderId: '624028473738',
    projectId: 'reading-app-da2c7',
    databaseURL: 'https://reading-app-da2c7.firebaseio.com',
    storageBucket: 'reading-app-da2c7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAfcaRaMNz9-KkzB2wn47ZJMFahZcthYg',
    appId: '1:624028473738:web:d694553a92d2c32e855073',
    messagingSenderId: '624028473738',
    projectId: 'reading-app-da2c7',
    authDomain: 'reading-app-da2c7.firebaseapp.com',
    databaseURL: 'https://reading-app-da2c7.firebaseio.com',
    storageBucket: 'reading-app-da2c7.firebasestorage.app',
    measurementId: 'G-XG9NKMSB7K',
  );

}